version: '2'
services:

  web:
    build: .
    working_dir: /viron
    depends_on:
      - api
    ports:
      - 8080:8080
    environment:
      - SHELL=/bin/bash
    volumes:
      - ./.editorconfig:/viron/.editorconfig
      - ./.eslintrc.js:/viron/.eslintrc.js
      - ./.stylefmtrc:/viron/.stylefmtrc
      - ./.stylelintrc:/viron/.stylelintrc
      - ./package-lock.json:/viron/package-lock.json
      - ./package.json:/viron/package.json
      - ./postcss.config.js:/viron/postcss.config.js
      - ./public:/viron/public
      - ./rollup.base.config.js:/viron/rollup.base.config.js
      - ./rollup.config.js:/viron/rollup.config.js
      - ./rollup.local.config.js:/viron/rollup.local.config.js
      - ./src:/viron/src
      - ./task:/viron/task
      - ./test:/viron/test
    command: npm run start

  api:
    build: ./demo
    working_dir: /demo
    depends_on:
      - mysql
    ports:
      - 3000:3000
      - 53000:53000
    environment:
      - SERVICE_ENV=local
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
    volumes:
      - ./demo/package.json:/demo/package.json
      - ./demo/shared:/demo/shared
      - ./demo/config:/demo/config
      - ./demo/app.js:/demo/app.js
      - ./demo/controllers:/demo/controllers
      - ./demo/fittings:/demo/fittings
      - ./demo/swagger:/demo/swagger
      - ./demo/test:/demo/test
      - ./demo/.env.template:/demo/.env
    command: npm run inspect

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - $PWD/.docker/mysql/data:/var/lib/mysql
    env_file:
      - ./mysql.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      default:
        aliases:
          - viron.dev
